import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono, Inter, Manrope } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
export const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "NexaFx",
  description: "NexaFx Web Application",
>>>>>>> 764c305853999c314cc80ab46a510043b8848d49
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${inter.variable} ${manrope.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
=======
      <body className={`${inter.variable} antialiased`}>{children}</body>
>>>>>>> 764c305853999c314cc80ab46a510043b8848d49
    </html>
  );
}
